version: '3.8'
services:
  nginx_temp:
    image: nginx:latest
    container_name: nginx_temp_certbot
    ports:
      - "80:80"
    volumes:
      - ./certbot/www:/usr/share/nginx/html
    command: >
      bash -c "mkdir -p /usr/share/nginx/html/.well-known/acme-challenge &&
               echo 'Servidor temporal activo para Certbot' &&
               nginx -g 'daemon off;'"
